### ISSUE TITLE
[FEATURE] Logo Design

### ISSUE THREAD

**Issue by YuriDevAT** [YurisCodingClub/dev-cv#1]
### Description

Create a Logo DevCV which will be showcased later on in the Header and/or Footer as well as Icon.

### Acceptance Criteria

- [ ] The Logo's color is accessible. For more information check out [WebAIM's article about color contrast](https://webaim.org/articles/contrast/). 
- [ ] The Logo is saved as SVG called logo.svg
- [ ] The Icon is saved as favicon.ico
- [ ] A folder is created in the public directory and called "images"
- [ ] The Logo is saved in the new folder called "images"
- [ ] The old favicon from react is replaced by the new created favicon

### Additional information

If you do not know how to use git, no worries. I will help you with it to make sure you get the Hacktoberfest-accepted badge.

**Comment by Nikhil-1503** [comment]
Hello Yuri,
I would love to work on this.

**Comment by Mustafa-Azad025** [comment]
hey @YuriDevAT ,
Please Assign This Task To Me

**Comment by marinoffDev** [comment]
hey @YuriDevAT could I work on this?

**Comment by Mustafa-Azad025** [comment]
Hey @YuriDevAT ,
I have Update the icon and favicon and placed as you suggested please review and merge this.

**Comment by YuriDevAT** [comment]
Hi @Mustafa-Azad025 . Thanks for you respond. I don't merge PRs just for the sake of Hacktoberfest.

Maybe it would be best to add some examples here after doing research what style could be a good fit and decide afterward how the logo should look like and going into designing.

**Comment by Mustafa-Azad025** [comment]
Yah @YuriDevAT ,
I understand and will give design according to your example.

**Comment by YuriDevAT** [comment]
Let's collect some ideas in the [discussion thread for Logo Design](https://github.com/YurisCodingClub/dev-cv/discussions/27). ✨

**Comment by sowmiya-venkatesan** [comment]
Could you please assign me this issue @YuriDevAT

**Comment by YuriDevAT** [comment]
Hey @sowmiya-venkatesan thanks for your comment. As mentioned the logo design will be discussed under the discussion section before someone actually starts to desgin it. Your input is very welcome in this section.

**Comment by sowmiya-venkatesan** [comment]
> Hey @sowmiya-venkatesan thanks for your comment. As mentioned the logo design will be discussed under the discussion section before someone actually starts to desgin it. Your input is very welcome in this section. [discussion thread for Logo Design](https://github.com/YurisCodingClub/dev-cv/discussions/27). ✨

Thanks for making me a contributor :)
Could you please let me know, what are the colors you prefer?

**Comment by sowmiya-venkatesan** [comment]
Please check the PR [#2](https://github.com/sowmiya-venkatesan/dev-cv/pull/2)
