### ISSUE TITLE
[FEATURE] Header

### ISSUE THREAD

**Issue by YuriDevAT** [YurisCodingClub/dev-cv#2]
### Description

Create a Header with any logo as a placeholder until #1 is finished. (Will be another issue).

### Acceptance Criteria (AC)

- [ ] Create a component called `Header.js` and save it in a folder called **components** in the `src` directory
- [ ] A header is shown with a logo and the name in it
- [ ] Plain HTML, no styling added
- [ ] The header meets accessibility standards like semantic HTML
- [ ] The header is fixed (stays at its position even when scrolling)
- [ ] The new component is imported and displayed in the `App.js` component
- [ ] Only the new component is displayed

**Comment by Mohit-Aasirwal** [comment]
hey! I can make this. Please assign me for this task

**Comment by Mustafa-Azad025** [comment]
hey,
I can make logo for you. please assign task to me.

**Comment by Dhanshriborse** [comment]
Hey ! I can do this very well. Please assign this to me.

**Comment by Tusharjain123** [comment]
Hey @YuriDevAT, Can I work on this issue?

**Comment by Saptadev-Chatterjee** [comment]
I can do this. I am a beginner in web development and want to contribute. Can I work on the issue ?

**Comment by DugarRishab** [comment]
Hey, can I want to contribute to this issue
