### ISSUE TITLE
Add space to main to avoid being cut off from Header

### ISSUE THREAD

**Issue by YuriDevAT** [YurisCodingClub/dev-cv#21]
### Description

Since the position of the header is fixed it cuts off part of the main content. Add space to the main content in be fully visible.

### Acceptance criteria

- [ ] Space is added to avoid main content from being cut off
- [ ] After some research the most appropriate CSS attribute is chosen (margin, padding, ..)

### Screenshots

<img width="595" alt="Header cuts off main content" src="https://user-images.githubusercontent.com/54622834/194748691-a3fe1024-400c-465d-bcb5-9b9f6ed4ec3a.png">

**Comment by ShishuSidharth** [comment]
can you please assign this to me

**Comment by Volley-Freak** [comment]
Hey @YuriDevAT , I would like to resolve this issue and make it better. You can assign this to me

**Comment by sidmadke** [comment]
@YuriDevAT I can fix this instantly. Can you please assign me this task?

**Comment by YuriDevAT** [comment]
> can you please assign this to me

Sure @ShishuSidharth , go ahead 👍🏽

**Comment by ShishuSidharth** [comment]
Thanks @YuriDevAT
