### ISSUE TITLE
App Design

### ISSUE THREAD

**Issue by volley-freak** [YurisCodingClub/dev-cv#23]
### What would you like to share?

All the input box should be styled to look cool.

### Additional information

Input boxes with label can be styled with MUI to look cool.

**Comment by YuriDevAT** [comment]
Hi @Volley-Freak. Thank you for the issue. You are right. Please go to the [discussions section of the project](https://github.com/YurisCodingClub/dev-cv/discussions) where I opened a discussion about the app's design and work together on a great design for the app.
