### ISSUE TITLE
[FEATURE] Form Personal Information

### ISSUE THREAD

**Issue by YuriDevAT** [YurisCodingClub/dev-cv#3]
### Description

As a User, I want to see a form in which I can add my personal information.

### Create a form with following input elements

- [ ] Fullname (required)
- [ ] Job Title 
- [ ] Email
- [ ] Phone number
- [ ] Address (simplified)
- [ ] Link to GitHub (recommended)
- [ ] Link to Portfolio (optional)
- [ ] Link to Linkedin (optional)
- [ ] Save button
- [ ] Cancel button

### Acceptance Criteria (AC) for beginners

- [ ] Create a component called `PersonalInformation.js` and save it in a folder called **components** in the `src` directory
- [ ] Heading: Personal Information
- [ ] Form with above mentioned fields
- [ ] Inputfields must be editable
- [ ] Fullname throws error when not filled out
- [ ] Input fields are [accessible](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form) 
- [ ] Save button does not require functionality
- [ ] No stylings but plain html
- [ ] The new component is imported and displayed in the `App.js` component
- [ ] Only the new component is displayed

### Additional AC if you are more experienced

- [ ] Save data in localStorage

### Additional information

Please do not hesitate to ask me about accessible forms in case you are unsure.
Accessibility and your inexperience with this topic should not be the reason you are not work on this issue, but to learn about it.

**Comment by brandonmcconnell** [comment]
@YuriDevAT Where would you want this form added? Is there a specific page in your codebase you have allocated for this?

**Comment by YuriDevAT** [comment]
@brandonmcconnell Thanks for pointing that out. 🤝  I added the information in every issue. Do you want to get assigned to this issue?

**Comment by Fomonyuytar-Joseph** [comment]
Hello @YuriDevAT  ,Please i would love to contributte to this project
