### ISSUE TITLE
Destructuring Header Component: Download button not visible

### ISSUE THREAD

**Issue by YuriDevAT** [YurisCodingClub/dev-cv#30]
### Description

Currently, the download button is not visible but lies under the header component. Also, the header component has no header tag and is therefore not accessible.

## Acceptance criteria

- [ ] change the `nav` to `header` tag (since there is no navigation the `nav` would be inaccurate to use)
- [ ] delete all unnecessary tags
- [ ] wrap logo and name into the same tag
- [ ] set the alt text of the logo image to `alt=""`
- [ ] change `h2` of Name to `span`, with no className
- [ ] add `DownloadButton.js` into the `Header.js` component, after the logo
- [ ] use `display: flex`, and `justify-content: space-between` to let the logo appear on the left and the DownloadButton appear on the right side
- [ ] delete all unused CSS for this component
- [ ] move and adjust the `inline style` of the button into the `index.css` file.
- [ ] move content of `Header.css` to `index.css` (and delete the now empty component)
- [ ] change backgroung-color of `nav` to white and [set a box-shadow](https://www.cssmatic.com/box-shadow)

**Write className like**
header, header-logo, button-download

## Header component

<img width="637" alt="Header component with a logo and name placeholder. Download button cannot be seen" src="https://user-images.githubusercontent.com/54622834/195973971-6ecc2077-f033-4cfe-8deb-032d9a5b8c1d.png">

## Source code
<img width="497" alt="Source code of header component and download button" src="https://user-images.githubusercontent.com/54622834/195973998-c5baf1f6-832b-487a-860c-4756d788bf55.png">

### Additional information

Please make sure your fork has the latest updates before opening a pull request (PR).

**Comment by jsvigneshkanna** [comment]
@YuriDevAT , assign me this issue

**Comment by LittleMissButtons** [comment]
Hiya, please could you assign this to me and I'll have a go following the notes you made and let you know if I have any queries.
Thanks, Alexis

**Comment by YuriDevAT** [comment]
Nice to have you on board, @LittleMissButtons. 🔥
