### ISSUE TITLE
Personal Information Accessibility Issue

### ISSUE THREAD

**Issue by YuriDevAT** [YurisCodingClub/dev-cv#32]
### Description

1. Make sure all input fields are accessible.

Currently, the axe DevTools are showing that

> 
> Issue Description
> 
> Ensures every id attribute value used in ARIA and in labels is unique

To reproduce the issue, install the axe DevTools extension and run it.

### Additional information

For further instructions on how to make the component accessible, please read the following:

- [Form field multiple labels](https://dequeuniversity.com/rules/axe/4.4/form-field-multiple-labels?application=AxeFirefox)
- [IDs used in ARIA and labels must be unique ](https://dequeuniversity.com/rules/axe/4.4/duplicate-id-aria?application=AxeFirefox)

**Comment by MonicaFidalgo** [comment]
hI @YuriDevAT thanks for the suggestion! Yes please I would love to be assigned to this issue

**Comment by YuriDevAT** [comment]
Happy to have you contributing 🙂

**Comment by MonicaFidalgo** [comment]
Okie, done! I actually needed to create 2 branches, in the first one I was fixing several accessibility issues, and I found other issues assigned for that ahah.  I didnt know about axe Devtools! Thanks @YuriDevAT :)
here goes the [pr](https://github.com/YurisCodingClub/dev-cv/pull/37)

**Comment by YuriDevAT** [comment]
I am glad you learned something new :)
