### ISSUE TITLE
[FEATURE] Form Programming Expertise

### ISSUE THREAD

**Issue by YuriDevAT** [YurisCodingClub/dev-cv#4]
### Description

As a User, I want to see a form in which I can add my programming expertise.

### Create a form with following input elements

- [ ] Title
- [ ] Subtitle 
- [ ] City
- [ ] Country
- [ ] Start Date
- [ ] End Date
- [ ] Description
- [ ] Save button
- [ ] Cancel button

### Acceptance Criteria (AC) for beginners

- [ ] Create a component called `ProgrammingExpertise.js` and save it in a folder called **components** in the `src` directory
- [ ] Heading: Programming Expertise
- [ ] Form with above mentioned fields
- [ ] Inputfields must be editable
- [ ] Input fields are [accessible](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form) 
- [ ] Save button does not require functionality
- [ ] No stylings but plain html
- [ ] The new component is imported and displayed in the `App.js` component
- [ ] Only the new component is displayed

### Additional AC if you are more experienced

- [ ] Save data in localStorage

### Additional information

Please do not hesitate to ask me about accessible forms in case you are unsure.
Accessibility and your inexperience with this topic should not be the reason you are not work on this issue, but to learn about it.

**Comment by Manthan-Kuber** [comment]
@YuriDevAT I am willing to take up this issue. Can you assign it to me

**Comment by Manthan-Kuber** [comment]
@YuriDevAT Hi about the styling...I am not allowed to even use layout related styles? Just input fields one below another right? Also we want to save form state in the local storage after the user clicks save ?

**Comment by Manthan-Kuber** [comment]
@YuriDevAT  
![image](https://user-images.githubusercontent.com/67104856/193291843-ce85e57c-f18f-45c8-b96d-82c0e97719fc.png)
Have created controlled inputs. Save button stores the state to localstorage. cancel button only clears the form state. Lmk if there are any changes to be made. I'll raise a PR when its Oct 1st in my country
