### ISSUE TITLE
[FEATURE] Add Tailwind CSS for styling and responsiveness

### ISSUE THREAD

**Issue by hariscs** [YurisCodingClub/dev-cv#47]
### Description

This app doesn't have any styling and it's not responsive on small screens.
i suggest we should add tailwind CSS to it for styling. tailwind is easy to set up and there are a lot of developers using it.

**Comment by YuriDevAT** [comment]
Good suggestion, @hariscs . Do you want to work on this issue?

**Comment by hariscs** [comment]
yes, i would like to
