### ISSUE TITLE
[FEATURE] Form Professional Experience

### ISSUE THREAD

**Issue by YuriDevAT** [YurisCodingClub/dev-cv#5]
### Description

As a User, I want to see a form in which I can add my professional experience.

### Create a form with following input elements

- [ ] Title
- [ ] Subtitle 
- [ ] City
- [ ] Country
- [ ] Start Date
- [ ] End Date
- [ ] Description
- [ ] Save button
- [ ] Cancel button

### Acceptance Criteria (AC) for beginners

- [ ] Create a component called `ProfessionalExperience.js` and save it in a folder called **components** in the `src` directory
- [ ] Heading: Professional Experience
- [ ] Form with above mentioned fields
- [ ] Inputfields must be editable
- [ ] Input fields are [accessible](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form) 
- [ ] Save button does not require functionality
- [ ] No stylings but plain html
- [ ] The new component is imported and displayed in the `App.js` component
- [ ] Only the new component is displayed

### Additional AC if you are more experienced

- [ ] Save data in localStorage

### Additional information

Please do not hesitate to ask me about accessible forms in case you are unsure.
Accessibility and your inexperience with this topic should not be the reason you are not work on this issue, but to learn about it.

**Comment by ChaudharyRaman** [comment]
Hi , i  want to contribute to this issue . could you please assign it to me @YuriDevAT ?

**Comment by utkarsh1311** [comment]
I would like to work on this if it is available.

**Comment by YuriDevAT** [comment]
Hey @ChaudharyRaman! I wanted to ask if you actively working on this issue? Otherwise I would assign it to someone else. Please let me know if you have any questions.
