### ISSUE TITLE
[FEATURE] Form Skills

### ISSUE THREAD

**Issue by YuriDevAT** [YurisCodingClub/dev-cv#6]
### Description

As a User, I want to see a form in which I can add my skills.

### Create a form with following input elements

- [ ] Technical skills
- [ ] Business Skills
- [ ] Programming Languages
- [ ] Tools
- [ ] Languages
- [ ] Save button
- [ ] Cancel button

### Acceptance Criteria (AC) for beginners

- [ ] Create a component called `Skills.js` and save it in a folder called **components** in the `src` directory
- [ ] Heading: Skills
- [ ] Form with above mentioned fields
- [ ] Inputfields must be editable
- [ ] Input fields are [accessible](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form) 
- [ ] Save button does not require functionality
- [ ] No stylings but plain html
- [ ] The new component is imported and displayed in the `App.js` component
- [ ] Only the new component is displayed

### Additional AC if you are more experienced

- [ ] Save data in localStorage

### Additional information

Please do not hesitate to ask me about accessible forms in case you are unsure.
Accessibility and your inexperience with this topic should not be the reason you are not work on this issue, but to learn about it.

**Comment by varun7singh** [comment]
working on this

**Comment by Fomonyuytar-Joseph** [comment]
Please can I be assigned to this task ?
