### ISSUE TITLE
[FEATURE] Form Certificates

### ISSUE THREAD

**Issue by YuriDevAT** [YurisCodingClub/dev-cv#8]
### Description

As a User, I want to see a form in which I can add my certificates.

### Create a form with following input elements

- [ ] Certificates
- [ ] Additional Information
- [ ] Save Button
- [ ] Cancel Button

### Acceptance Criteria (AC) for beginners

- [ ] Create a component called `Certificates.js` and save it in a folder called **components** in the `src` directory
- [ ] Heading: Certificates
- [ ] Form with above mentioned fields
- [ ] Inputfields must be editable
- [ ] Input fields are [accessible](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form) 
- [ ] Save button does not require functionality
- [ ] No stylings but plain html
- [ ] The new component is imported and displayed in the `App.js` component
- [ ] Only the new component is displayed

### Additional AC if you are more experienced

- [ ] Save data in localStorage

### Additional information

Please do not hesitate to ask me about accessible forms in case you are unsure.
Accessibility and your inexperience with this topic should not be the reason you are not work on this issue, but to learn about it.

**Comment by ChaudharyRaman** [comment]
HI, I would like to contribute to this issue . can you assign it to me @YuriDevAT ?

**Comment by YuriDevAT** [comment]
Sure @ChaudharyRaman 🙂

**Comment by YuriDevAT** [comment]
Hey @ChaudharyRaman! I wanted to ask if you actively working on this issue? Otherwise I would assign it to someone else. Please let me know if you have any questions.

**Comment by hariscs** [comment]
hi @YuriDevAT, i would like to work on this issue

**Comment by YuriDevAT** [comment]
Sure @hariscs, go ahead 🙂
