### ISSUE TITLE
[FEATURE] Button Download

### ISSUE THREAD

**Issue by YuriDevAT** [YurisCodingClub/dev-cv#9]
### Description

Create a button called Download with an icon next to the text.

### Acceptance Criteria (AC)

- [ ] Create a component called `DownloadButton.js` and save it in a folder called **components** in the `src` directory
- [ ] The icon has to be an svg
- [ ] Create a folder in the public directory and call it "images"
- [ ] Save the svg in the new folder called "images"
- [ ] Button does not require functionality
- [ ] No stylings but plain html
- [ ] The new component is imported and displayed in the `App.js` component
- [ ] Only the new component is displayed

### Additional information

Please do not hesitate to ask me about accessible forms in case you are unsure.
Accessibility and your inexperience with this topic should not be the reason you are not work on this issue, but to learn about it.

**Comment by DugarRishab** [comment]
hi, I would like to contribute to this project. Could you please explain more about where his component should be included?

**Comment by YuriDevAT** [comment]
Hey @DugarRishab thanks for pointing this out. I added the information in every issue. 👍🏽

**Comment by DugarRishab** [comment]
@YuriDevAT Please look into all the un-closed PRs. I believe all PRs are facing the same issue mine included. Could you please guide us to resolve it?

**Comment by YuriDevAT** [comment]
Thank you for your comment. I will look into it on Wednesday, since I have currently no access to a computer.
